#!/bin/bash echo ALX School is so cool
##1/bin/bash echo ALX School
#!/bin/bash echo ALX School is so cool

#1/bin/bash echo ALX School is so cool
##!/bin/bash echo ALX School
#!/bin/bash echo AlX School

